name: Run sqlancer on release branch

on:
  push:
    branches: "**"
  workflow_dispatch:
    inputs:
      citus_release:
        default: release-11.1
    image_suffix:
      default: '-v7e4468f'

env:
  timeout: ${{ inputs.timeout }}
  citus_release: ${{ inputs.citus_release }}

jobs:

  run-sqlancer-test-on-citus:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container:
      image: 'citus/extbuilder:15.1-v7e4468f'

    steps:
      - name: Set pg_config path
        run: |
          echo "PG_CONFIG=/usr/lib/postgresql/15/bin" >> $GITHUB_PATH

      - name: Checkout citus release
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.citus_release }}
          repository: citusdata/citus

      - name: Configure
        run: |
          echo "Current Shell:$0"
          echo "GCC Version: $(gcc --version)"
          ./configure 2>&1 | tee output.log

      - name: Make install-all
        run: |
          make install-all -sj$(cat /proc/cpuinfo | grep "core id" | wc -l) 2>&1 | tee -a output.log

      - name: Checkout Sqlancer
        uses: actions/checkout@v3
        with:
          ref: master
          repository: sqlancer/sqlancer

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Build SQLancer
        run: mvn -B package -DskipTests=true

      - name: Set up Citus cluster
        run: |
          cd ~
          mkdir -p citus/coordinator citus/worker1 citus/worker2
          initdb -D citus/coordinator
          initdb -D citus/worker1
          initdb -D citus/worker2
          echo "shared_preload_libraries = 'citus'" >> citus/coordinator/postgresql.conf
          echo "shared_preload_libraries = 'citus'" >> citus/worker1/postgresql.conf
          echo "shared_preload_libraries = 'citus'" >> citus/worker2/postgresql.conf
          pg_ctl -D citus/coordinator -o "-p 9700" -l coordinator_logfile start || cat coordinator_logfile || cat citus/coordinator/coordinator_logfile
          pg_ctl -D citus/worker1 -o "-p 9701" -l worker1_logfile start
          ls citus/worker1
          pg_ctl -D citus/worker2 -o "-p 9702" -l worker2_logfile start
          psql -c "CREATE ROLE sqlancer SUPERUSER LOGIN CREATEDB PASSWORD 'sqlancer';" -p 9700 -d postgres -U $USER
          createdb test -p 9700 -U $USER
          psql -c "CREATE ROLE sqlancer SUPERUSER LOGIN CREATEDB PASSWORD 'sqlancer';" -p 9701 -d postgres -U $USER
          createdb test -p 9701 -U $USER
          psql -c "CREATE ROLE sqlancer SUPERUSER LOGIN CREATEDB PASSWORD 'sqlancer';" -p 9702 -d postgres -U $USER
          createdb test -p 9702 -U $USER
          psql -c "CREATE EXTENSION citus;" -p 9700 -U $USER -d test
          psql -c "CREATE EXTENSION citus;" -p 9701 -U $USER -d test
          psql -c "CREATE EXTENSION citus;" -p 9702 -U $USER -d test
          psql -c "SELECT * from citus_add_node('localhost', 9701);" -p 9700 -U $USER -d test
          psql -c "SELECT * from citus_add_node('localhost', 9702);" -p 9700 -U $USER -d test

      - name: Run Tests
        run: CITUS_AVAILABLE=true mvn -Dtest=TestCitus test
