name: Run sqlancer on release branch

on:
  push:
    branches: "**"
  workflow_dispatch:
    inputs:
      citus_release:
        default: release-11.1

env:
  timeout: ${{ inputs.timeout }}
  citus_release: ${{ inputs.citus_release }}

# defaults:
#   run:
#     shell: bash
#     working-directory: /home/circleci

jobs:

  run-sqlancer-test-on-citus:
    runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    container:
      image: 'citus/exttester:15.1-dev-895be1f'
      #options: --user circleci

    steps:
      # - name: install dependencies
      #   run: |
      #     sudo apt-get update
      #     sudo apt-get -y install --no-install-recommends \
      #       apt-transport-https \
      #       autoconf \
      #       build-essential \
      #       ca-certificates \
      #       curl \
      #       debian-archive-keyring \
      #       gcc \
      #       gnupg \
      #       gosu \
      #       libcurl4 \
      #       libcurl4-openssl-dev \
      #       libicu-dev \
      #       liblz4-1 \
      #       liblz4-dev \
      #       libreadline-dev \
      #       libselinux1-dev \
      #       libssl-dev \
      #       libxslt-dev \
      #       libzstd-dev \
      #       libzstd1 \
      #       locales \
      #       make \
      #       perl \
      # - name: install pg 15.1
      #   run: |
      #     sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
      #     wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
      #     sudo apt-get update
      #     sudo apt-get -y install postgresql-15

      # - name: Set pg bin path
      #   run: |
      #     echo "/usr/lib/postgresql/15/bin" >> $GITHUB_PATH

      - name: Checkout citus release
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.citus_release }}
          repository: citusdata/citus

      - name: Configure
        run: |
          echo "Current Shell:$0"
          echo "GCC Version: $(gcc --version)"
          ./configure 2>&1 | tee output.log

      - name: Make install-all
        run: |
          make install-all -sj$(cat /proc/cpuinfo | grep "core id" | wc -l) 2>&1 | tee -a output.log

      - name: Setup Maven
        uses: s4u/setup-maven-action@v1.6.0
        with:
          java-version: 11

      - name: Checkout Sqlancer
        uses: actions/checkout@v3
        with:
          ref: master
          repository: sqlancer/sqlancer

      - name: Build SQLancer
        run: mvn -B package -DskipTests=true

      - name: Set up Citus cluster
        run: |
          gosu circleci mkdir -p citus/coordinator citus/worker1 citus/worker2
          gosu circleci initdb -D citus/coordinator
          gosu circleci initdb -D citus/worker1
          gosu circleci initdb -D citus/worker2
          gosu circleci echo "shared_preload_libraries = 'citus'" >> citus/coordinator/postgresql.conf
          gosu circleci echo "shared_preload_libraries = 'citus'" >> citus/worker1/postgresql.conf
          gosu circleci echo "shared_preload_libraries = 'citus'" >> citus/worker2/postgresql.conf
          gosu circleci pg_ctl -D citus/coordinator -o "-p 9700" -l coordinator_logfile start || cat coordinator_logfile || cat citus/coordinator/coordinator_logfile
          gosu circleci pg_ctl -D citus/worker1 -o "-p 9701" -l worker1_logfile start
          gosu circleci ls citus/worker1
          gosu circleci pg_ctl -D citus/worker2 -o "-p 9702" -l worker2_logfile start
          gosu circleci psql -c "CREATE ROLE sqlancer SUPERUSER LOGIN CREATEDB PASSWORD 'sqlancer';" -p 9700 -d postgres -U $USER
          gosu circleci createdb test -p 9700 -U $USER
          gosu circleci psql -c "CREATE ROLE sqlancer SUPERUSER LOGIN CREATEDB PASSWORD 'sqlancer';" -p 9701 -d postgres -U $USER
          gosu circleci createdb test -p 9701 -U $USER
          gosu circleci psql -c "CREATE ROLE sqlancer SUPERUSER LOGIN CREATEDB PASSWORD 'sqlancer';" -p 9702 -d postgres -U $USER
          gosu circleci createdb test -p 9702 -U $USER
          gosu circleci psql -c "CREATE EXTENSION citus;" -p 9700 -U $USER -d test
          gosu circleci psql -c "CREATE EXTENSION citus;" -p 9701 -U $USER -d test
          gosu circleci psql -c "CREATE EXTENSION citus;" -p 9702 -U $USER -d test
          gosu circleci psql -c "SELECT * from citus_add_node('localhost', 9701);" -p 9700 -U $USER -d test
          gosu circleci psql -c "SELECT * from citus_add_node('localhost', 9702);" -p 9700 -U $USER -d test

      - name: Run Tests
        run: CITUS_AVAILABLE=true mvn -Dtest=TestCitus test
